name: snakemake
channels:
  - conda-forge
  - bioconda
dependencies:
  - python   # or 2.7
  - pims
  - ipython
  - mamba
  - pip
  - numpy
  - scikit-learn
  - singularity
  - snakemake
  - pip:
    - ome-zarr
